channels:
 - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pyyaml
  - scipy
  - ipython
  - pandas
  - jupyter
  - ipykernel
  - scikit-learn
  - selenium
  - phantomjs
  - pillow
  - bokeh=0.13.0
  - jupytext
  - pip:
    - https://github.com/theskumar/python-dotenv/archive/master.zip
    - docker
